"""Constants for the Power Watchdog WiFi integration."""

DOMAIN = "power_watchdog_wifi"
PLATFORMS = ["sensor", "binary_sensor"]

# Config-entry keys persisted from config flow / cloud metadata.
CONF_ACCOUNT = "account"
CONF_PASSWORD = "password"
CONF_DEVICE_NO = "device_no"
CONF_DEVICE_ID = "device_id"
CONF_DEVICE_NAME = "device_name"
CONF_FIRMWARE = "firmware"
CONF_MCU_FIRMWARE = "mcu_firmware"
CONF_CONNECT_TYPE = "connect_type"
CONF_SOCKET_STATE = "socket_state"
CONF_START_FROM = "start_from"
CONF_CONNECTION_MODE = "connection_mode"
CONF_POLL_INTERVAL_MINUTES = "poll_interval_minutes"

CONNECTION_MODE_ALWAYS_ON = "always_on"
CONNECTION_MODE_POLLING = "polling"
CONNECTION_MODES = (CONNECTION_MODE_POLLING, CONNECTION_MODE_ALWAYS_ON)

DEFAULT_CONNECTION_MODE = CONNECTION_MODE_POLLING
DEFAULT_POLL_INTERVAL_MINUTES = 10
POLL_INTERVAL_MINUTES_ALLOWED = (1, 2, 5, 10, 15, 30, 60)

API_BASE_URL = "https://api.watchdogsrv.com/api"
WS_URL = "ws://ws.watchdogsrv.com:5521/ws"
APP_VERSION = "1.0.15"
APP_DEVICE = "android"

# Runtime tuning defaults.
WS_RECONNECT_MIN_SECONDS = 5
WS_RECONNECT_MAX_SECONDS = 300
TELEMETRY_AVAILABILITY_TIMEOUT_SECONDS = 120
DEVICE_METADATA_REFRESH_INTERVAL_SECONDS = 3600
DERIVED_ROLLING_POWER_WINDOW_SECONDS = 300
DERIVED_ENERGY_STATE_PERSIST_INTERVAL_SECONDS = 300
DERIVED_ENERGY_STORAGE_KEY = "power_watchdog_wifi_derived_energy"
DERIVED_ENERGY_STORAGE_VERSION = 1

# Polling-mode tuning defaults.
POLL_CAPTURE_TIMEOUT_SECONDS = 30
POLL_JITTER_RATIO = 0.10
POLL_JITTER_MAX_SECONDS = 60
